random_words = [
    "apple",
    "mountain",
    "galaxy",
    "river",
    "elephant",
    "breeze",
    "chocolate",
    "whisper",
    "puzzle",
    "sunflower",
    "comet",
    "mystery",
    "ocean",
    "thunder",
    "harmony",
    "candle",
    "journey",
    "shadow",
    "lullaby",
    "quicksilver",
    "echo",
    "serendipity",
    "riddle",
    "ember",
    "quartz",
    "voyage",
    "feather",
    "mirage",
    "whisker",
    "starlight"
]

famous_movies = [
    "The Godfather",
    "The Shawshank Redemption",
    "Schindler's List",
    "Pulp Fiction",
    "The Dark Knight",
    "Forrest Gump",
    "Inception",
    "Fight Club",
    "The Lord of the Rings: The Return of the King",
    "Star Wars: Episode IV - A New Hope",
    "The Matrix",
    "The Silence of the Lambs",
    "Casablanca",
    "Titanic",
    "The Godfather: Part II",
    "Goodfellas",
    "The Empire Strikes Back",
    "The Lion King",
    "Saving Private Ryan",
    "Jurassic Park",
    "Back to the Future",
    "Gladiator",
    "Braveheart",
    "Avatar",
    "The Departed",
    "The Shining",
    "One Flew Over the Cuckoo's Nest",
    "Gone with the Wind",
    "Jaws",
    "ET the Extra Terrestrial",
    "Indiana Jones: Raiders of the Lost Ark",
    "The Green Mile",
    "Apocalypse Now",
    "The Good, the Bad and the Ugly",
    "12 Angry Men",
    "The Social Network",
    "Django Unchained",
    "Alien",
    "Rocky",
    "The Terminator",
    "Blade Runner",
    "A Clockwork Orange",
    "Psycho",
    "The Big Lebowski",
    "Scarface",
    "The Usual Suspects",
    "Taxi Driver",
    "American History X",
    "The Sixth Sense",
    "The Grand Budapest Hotel"
]
